version: "3.7"


services:

    openccg:
        build: .
        ports:
            - "80:8080"
        environment:
            - DISPLAY=${IP}:0
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
