version: "3.2"


services:

    openccg:
        build: .

    nginx:
        build:
            dockerfile: nginx/Dockerfile
            context: .
        ports:
            - "80:80"
        depends_on:
            - openccg
