version: "3.2"


services:

    openccg:
        build: .
        ports:
            - "${OPENCCG_EXTERNAL_PORT:-80}:8080"
        networks:
            - external_network

networks:
    external_network:
        external:
            name: ${OPENCCG_NETWORK:-web-openccg_default}
