version: "3.2"


services:

    openccg:
        build: .
        ports:
            - "80:8080"
        networks:
            - external_network

networks:
    external_network:
        external:
            name: ${DOCKER_NETWORK:-web-openccg_default}
